apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  labels:
    app: mailhog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
      - name: mailhog
        image: mailhog/mailhog:latest
        ports:
        - containerPort: 1025
        - containerPort: 8025

---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  ports:
  - protocol: TCP
    name: web-poer
    targetPort: 8025 # ContainerPort
    port: 8025 # ServicePort
  - protocol: TCP
    name: smtp-port
    targetPort: 1025 # ContainerPort
    port: 1025 # ServicePort