version: '3'

services:
  brocker-service:
    build:
      context: ./brocker
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: ./logger
      dockerfile: Dockerfile
    env_file:
      - ./logger/.env
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - auth_db
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DATABASE_URL: "host=auth_db port=5432 user=postgres password=password dbname=users connect_timeout=5"

  auth_db:
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  logger_mongo_db:
    image: mongo:8.0.12-noble
    ports:
      - "27017:27017"
    env_file:
      - ./logger/.env
    volumes:
      - ./db-data/mongo/:/data/db

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  mailer-service:
    build:
      context: ./mailer
      dockerfile: Dockerfile
    env_file:
      - ./mailer/.env
    restart: always
    deploy:
      mode: replicated
      replicas: 1
