apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
# TODO: Security issue: using plain username && password => divide into smaller secret info and save into secret file.
  DATABASE_URL: "host=host.minikube.internal port=5432 user=postgres password=password dbname=users connect_timeout=5"
