apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  labels:
    app: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: aghaghia/broker-service:1.0.0
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: broker-config
        - secretRef:
            name: broker-secret
      imagePullSecrets:
      - name: my-docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: broker-service
  labels:
    app: broker
spec:
  selector:
    app: broker
  ports:
  - protocol: TCP
    targetPort: 80 # ContainerPort
    port: 8080 # ServicePort