apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  labels:
    app: logger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: aghaghia/logger-service:1.0.0
        ports:
        - containerPort: 80
        - containerPort: 5001
        - containerPort: 50001
        envFrom:
        - configMapRef:
            name: logger-config
        - secretRef:
            name: logger-secret
      # imagePullSecrets:
      # - name: my-docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: logger-service
  labels:
    app: logger
spec:
  selector:
    app: logger
  ports:
  - protocol: TCP
    name: web-port
    targetPort: 80 # ContainerPort
    port: 80 # ServicePort
  - protocol: TCP
    name: rpc-port
    targetPort: 5001 # ContainerPort
    port: 5001 # ServicePort
  - protocol: TCP
    name: grpc-port
    targetPort: 50001 # ContainerPort
    port: 50001 # ServicePort